### ISSUE TITLE
Error: Identifier not found "TListEx"

### ISSUE THREAD

**Issue by fibodevy** [AlexanderBagel/CPUView#1]
Doesnt compile on trunk since [#1354 FPC 3.2.2 support](https://github.com/AlexanderBagel/CPUView/commit/fead5a44974a7d93ffda8e3878b17657a96e76a2)

**Comment by AlexanderBagel** [comment]
This class was added in the FWHexView.LCL.lpk package to support the 3.2.2 compiler, so you will need to recompile that package to fix the error.
https://github.com/AlexanderBagel/FWHexView

Please check this.

**Comment by fibodevy** [comment]
Okay, thanks! Keep up the good work!

https://github.com/AlexanderBagel/FWHexView/commit/24cb3ac1901438cdfcc902ca183cbdbb5bccf08c#diff-c1b19b3920bdcd017de68b3773eb6825e307e4e626a84d9d04e59c7d51ed923cR81
